- hosts: local
  user: ram
  sudo: yes
  gather_facts: no
  tasks:
    - name: install tools
      yum: name={{ item }} state=installed update_cache=yes
      with_items:
       - httpd
       - solr
       - ZooKeeper
       - tomcat liferay bundle
      notify:
       - restart services
  handlers:
       - name: restart services
         service: name={{ httpd }} state=restarted 
         with_items:
           - httpd
           - solr
           - ZooKeeper
           - tomcat liferay bundle
 
      

